"rushingPlayers": {
    "Hunt, Kareem": {
    "GP": 16,
    "ATT": 272,
    "ATT/G": 17,
    "YDS": 46,
    "AVG": 4.9,
    "YDS/G": 82.9,
    "TD": 8,
    "LNG": 69,
    "BIG": 35,
    "100+": 6,
    "STUFF": 24,
    "FUM": 1,
    "FUML": 1,
    "1ST": 60,
    "PCT": "22.10%"
  },
  
    "Gurley II, Todd": {
    "GP": 15,
    "ATT": 279,
    "ATT/G": 18.6,
    "YDS": 70,
    "AVG": 4.7,
    "YDS/G": 87,
    "TD": 13,
    "LNG": 57,
    "BIG": 39,
    "100+": 6,
    "STUFF": 33,
    "FUM": 5,
    "FUML": 2,
    "1ST": 66,
    "PCT": "23.70%"
  },
  
    "Bell, Le'Veon": {
    "GP": 15,
    "ATT": 321,
    "ATT/G": 21.4,
    "YDS": 64,
    "AVG": 4,
    "YDS/G": 86.1,
    "TD": 9,
    "LNG": 27,
    "BIG": 33,
    "100+": 4,
    "STUFF": 27,
    "FUM": 2,
    "FUML": 2,
    "1ST": 74,
    "PCT": "23.10%"
  },
  
    "McCoy, LeSean": {
    "GP": 16,
    "ATT": 287,
    "ATT/G": 17.9,
    "YDS": 133,
    "AVG": 4,
    "YDS/G": 71.1,
    "TD": 6,
    "LNG": 48,
    "BIG": 33,
    "100+": 4,
    "STUFF": 55,
    "FUM": 3,
    "FUML": 1,
    "1ST": 56,
    "PCT": "19.50%"
  },
  
    "Ingram, Mark": {
    "GP": 16,
    "ATT": 230,
    "ATT/G": 14.4,
    "YDS": 26,
    "AVG": 4.9,
    "YDS/G": 70.3,
    "TD": 12,
    "LNG": 72,
    "BIG": 23,
    "100+": 4,
    "STUFF": 12,
    "FUM": 2,
    "FUML": 2,
    "1ST": 50,
    "PCT": "21.70%"
  },
  
    "Howard, Jordan": {
    "GP": 16,
    "ATT": 276,
    "ATT/G": 17.3,
    "YDS": 107,
    "AVG": 4.1,
    "YDS/G": 70.1,
    "TD": 9,
    "LNG": 53,
    "BIG": 32,
    "100+": 5,
    "STUFF": 44,
    "FUM": 1,
    "FUML": 1,
    "1ST": 61,
    "PCT": "22.10%"
  },
  
    "Gordon, Melvin": {
    "GP": 16,
    "ATT": 284,
    "ATT/G": 17.8,
    "YDS": 75,
    "AVG": 3.9,
    "YDS/G": 69.1,
    "TD": 8,
    "LNG": 87,
    "BIG": 34,
    "100+": 2,
    "STUFF": 37,
    "FUM": 1,
    "FUML": 0,
    "1ST": 58,
    "PCT": "20.40%"
  },
  
    "Fournette, Leonard": {
    "GP": 13,
    "ATT": 268,
    "ATT/G": 20.6,
    "YDS": 57,
    "AVG": 3.9,
    "YDS/G": 80,
    "TD": 9,
    "LNG": 90,
    "BIG": 18,
    "100+": 5,
    "STUFF": 32,
    "FUM": 2,
    "FUML": 0,
    "1ST": 46,
    "PCT": "17.20%"
  },
  
    "Anderson, C.J.": {
    "GP": 16,
    "ATT": 245,
    "ATT/G": 15.3,
    "YDS": 37,
    "AVG": 4.1,
    "YDS/G": 62.9,
    "TD": 3,
    "LNG": 40,
    "BIG": 21,
    "100+": 2,
    "STUFF": 21,
    "FUM": 1,
    "FUML": 1,
    "1ST": 47,
    "PCT": "19.20%"
  },
  
    "Elliott, Ezekiel": {
    "GP": 10,
    "ATT": 242,
    "ATT/G": 24.2,
    "YDS": 56,
    "AVG": 4.1,
    "YDS/G": 98.3,
    "TD": 7,
    "LNG": 30,
    "BIG": 21,
    "100+": 5,
    "STUFF": 19,
    "FUM": 1,
    "FUML": 1,
    "1ST": 55,
    "PCT": "22.70%"
  },
  
    "Collins, Alex": {
    "GP": 15,
    "ATT": 212,
    "ATT/G": 14.1,
    "YDS": 67,
    "AVG": 4.6,
    "YDS/G": 64.9,
    "TD": 6,
    "LNG": 50,
    "BIG": 27,
    "100+": 2,
    "STUFF": 29,
    "FUM": 2,
    "FUML": 2,
    "1ST": 51,
    "PCT": "24.10%"
  },
  
    "Gore, Frank": {
    "GP": 16,
    "ATT": 261,
    "ATT/G": 16.3,
    "YDS": 50,
    "AVG": 3.7,
    "YDS/G": 60.1,
    "TD": 3,
    "LNG": 21,
    "BIG": 19,
    "100+": 2,
    "STUFF": 26,
    "FUM": 3,
    "FUML": 0,
    "1ST": 49,
    "PCT": "18.80%"
  },
  
    "Hyde, Carlos": {
    "GP": 16,
    "ATT": 240,
    "ATT/G": 15,
    "YDS": 72,
    "AVG": 3.9,
    "YDS/G": 58.6,
    "TD": 8,
    "LNG": 61,
    "BIG": 27,
    "100+": 1,
    "STUFF": 33,
    "FUM": 2,
    "FUML": 1,
    "1ST": 44,
    "PCT": "18.30%"
  },
  
    "Lewis, Dion": {
    "GP": 16,
    "ATT": 180,
    "ATT/G": 11.3,
    "YDS": 38,
    "AVG": 5,
    "YDS/G": 56,
    "TD": 6,
    "LNG": 44,
    "BIG": 25,
    "100+": 2,
    "STUFF": 19,
    "FUM": 0,
    "FUML": 0,
    "1ST": 48,
    "PCT": "26.70%"
  },
  
    "Lynch, Marshawn": {
    "GP": 15,
    "ATT": 207,
    "ATT/G": 13.8,
    "YDS": 36,
    "AVG": 4.3,
    "YDS/G": 59.4,
    "TD": 7,
    "LNG": 51,
    "BIG": 21,
    "100+": 2,
    "STUFF": 21,
    "FUM": 1,
    "FUML": 1,
    "1ST": 44,
    "PCT": "21.30%"
  },
  
    "Miller, Lamar": {
    "GP": 16,
    "ATT": 238,
    "ATT/G": 14.9,
    "YDS": 43,
    "AVG": 3.7,
    "YDS/G": 55.5,
    "TD": 3,
    "LNG": 21,
    "BIG": 22,
    "100+": 0,
    "STUFF": 22,
    "FUM": 1,
    "FUML": 0,
    "1ST": 43,
    "PCT": "18.10%"
  },
  
    "Ajayi, Jay": {
    "GP": 14,
    "ATT": 208,
    "ATT/G": 14.9,
    "YDS": 77,
    "AVG": 4.2,
    "YDS/G": 62.4,
    "TD": 1,
    "LNG": 71,
    "BIG": 23,
    "100+": 2,
    "STUFF": 36,
    "FUM": 3,
    "FUML": 2,
    "1ST": 39,
    "PCT": "18.80%"
  },
  
    "Freeman, Devonta": {
    "GP": 14,
    "ATT": 196,
    "ATT/G": 14,
    "YDS": 32,
    "AVG": 4.4,
    "YDS/G": 61.8,
    "TD": 7,
    "LNG": 44,
    "BIG": 22,
    "100+": 2,
    "STUFF": 15,
    "FUM": 4,
    "FUML": 1,
    "1ST": 49,
    "PCT": "25.00%"
  },
  
    "Crowell, Isaiah": {
    "GP": 16,
    "ATT": 206,
    "ATT/G": 12.9,
    "YDS": 56,
    "AVG": 4.1,
    "YDS/G": 53.3,
    "TD": 2,
    "LNG": 59,
    "BIG": 22,
    "100+": 1,
    "STUFF": 20,
    "FUM": 1,
    "FUML": 1,
    "1ST": 38,
    "PCT": "18.40%"
  },
  
    "Murray, Latavius": {
    "GP": 16,
    "ATT": 216,
    "ATT/G": 13.5,
    "YDS": 50,
    "AVG": 3.9,
    "YDS/G": 52.6,
    "TD": 8,
    "LNG": 46,
    "BIG": 20,
    "100+": 2,
    "STUFF": 24,
    "FUM": 1,
    "FUML": 0,
    "1ST": 42,
    "PCT": "19.40%"
  },
  
    "Powell, Bilal": {
    "GP": 15,
    "ATT": 178,
    "ATT/G": 11.9,
    "YDS": 44,
    "AVG": 4.3,
    "YDS/G": 51.5,
    "TD": 5,
    "LNG": 75,
    "BIG": 20,
    "100+": 2,
    "STUFF": 24,
    "FUM": 0,
    "FUML": 0,
    "1ST": 30,
    "PCT": "16.90%"
  },
  
    "Blount, LeGarrette": {
    "GP": 16,
    "ATT": 173,
    "ATT/G": 10.8,
    "YDS": 55,
    "AVG": 4.4,
    "YDS/G": 47.9,
    "TD": 2,
    "LNG": 68,
    "BIG": 20,
    "100+": 1,
    "STUFF": 23,
    "FUM": 1,
    "FUML": 1,
    "1ST": 30,
    "PCT": "17.30%"
  },
  
    "Newton, Cam": {
    "GP": 16,
    "ATT": 139,
    "ATT/G": 8.7,
    "YDS": 15,
    "AVG": 5.4,
    "YDS/G": 47.1,
    "TD": 6,
    "LNG": 69,
    "BIG": 20,
    "100+": 0,
    "STUFF": 6,
    "FUM": 6,
    "FUML": 1,
    "1ST": 46,
    "PCT": "33.10%"
  },
  
    "Darkwa, Orleans": {
    "GP": 15,
    "ATT": 171,
    "ATT/G": 11.4,
    "YDS": 29,
    "AVG": 4.4,
    "YDS/G": 50.1,
    "TD": 5,
    "LNG": 75,
    "BIG": 16,
    "100+": 2,
    "STUFF": 12,
    "FUM": 1,
    "FUML": 0,
    "1ST": 33,
    "PCT": "19.30%"
  },
  
    "Henry, Derrick": {
    "GP": 16,
    "ATT": 176,
    "ATT/G": 11,
    "YDS": 77,
    "AVG": 4.2,
    "YDS/G": 46.5,
    "TD": 5,
    "LNG": 75,
    "BIG": 20,
    "100+": 2,
    "STUFF": 26,
    "FUM": 1,
    "FUML": 0,
    "1ST": 39,
    "PCT": "22.20%"
  },
  
    "Kamara, Alvin": {
    "GP": 16,
    "ATT": 120,
    "ATT/G": 7.5,
    "YDS": 21,
    "AVG": 6.1,
    "YDS/G": 45.5,
    "TD": 8,
    "LNG": 74,
    "BIG": 27,
    "100+": 1,
    "STUFF": 8,
    "FUM": 1,
    "FUML": 1,
    "1ST": 40,
    "PCT": "33.30%"
  },
  
    "Stewart, Jonathan": {
    "GP": 15,
    "ATT": 198,
    "ATT/G": 13.2,
    "YDS": 51,
    "AVG": 3.4,
    "YDS/G": 45.3,
    "TD": 6,
    "LNG": 60,
    "BIG": 15,
    "100+": 2,
    "STUFF": 22,
    "FUM": 3,
    "FUML": 3,
    "1ST": 41,
    "PCT": "20.70%"
  },
  
    "Murray, DeMarco": {
    "GP": 15,
    "ATT": 184,
    "ATT/G": 12.3,
    "YDS": 41,
    "AVG": 3.6,
    "YDS/G": 43.9,
    "TD": 6,
    "LNG": 75,
    "BIG": 9,
    "100+": 1,
    "STUFF": 17,
    "FUM": 1,
    "FUML": 1,
    "1ST": 29,
    "PCT": "15.80%"
  },
  
    "Drake, Kenyan": {
    "GP": 16,
    "ATT": 133,
    "ATT/G": 8.3,
    "YDS": 61,
    "AVG": 4.8,
    "YDS/G": 40.3,
    "TD": 3,
    "LNG": 66,
    "BIG": 16,
    "100+": 2,
    "STUFF": 21,
    "FUM": 2,
    "FUML": 2,
    "1ST": 24,
    "PCT": "18.00%"
  },
  
    "Coleman, Tevin": {
    "GP": 15,
    "ATT": 156,
    "ATT/G": 10.4,
    "YDS": 58,
    "AVG": 4,
    "YDS/G": 41.9,
    "TD": 5,
    "LNG": 52,
    "BIG": 14,
    "100+": 0,
    "STUFF": 21,
    "FUM": 1,
    "FUML": 0,
    "1ST": 27,
    "PCT": "17.30%"
  },
  
    "Mixon, Joe": {
    "GP": 14,
    "ATT": 178,
    "ATT/G": 12.7,
    "YDS": 72,
    "AVG": 3.5,
    "YDS/G": 44.7,
    "TD": 4,
    "LNG": 25,
    "BIG": 17,
    "100+": 1,
    "STUFF": 28,
    "FUM": 1,
    "FUML": 1,
    "1ST": 35,
    "PCT": "19.70%"
  },
  
    "Perine, Samaje": {
    "GP": 16,
    "ATT": 175,
    "ATT/G": 10.9,
    "YDS": 27,
    "AVG": 3.5,
    "YDS/G": 37.7,
    "TD": 1,
    "LNG": 30,
    "BIG": 13,
    "100+": 2,
    "STUFF": 17,
    "FUM": 2,
    "FUML": 2,
    "1ST": 22,
    "PCT": "12.60%"
  },
  
    "Allen, Javorius": {
    "GP": 16,
    "ATT": 153,
    "ATT/G": 9.6,
    "YDS": 36,
    "AVG": 3.9,
    "YDS/G": 36.9,
    "TD": 4,
    "LNG": 37,
    "BIG": 13,
    "100+": 0,
    "STUFF": 19,
    "FUM": 0,
    "FUML": 0,
    "1ST": 38,
    "PCT": "24.80%"
  },
  
    "Wilson, Russell": {
    "GP": 16,
    "ATT": 95,
    "ATT/G": 5.9,
    "YDS": 4,
    "AVG": 6.2,
    "YDS/G": 36.6,
    "TD": 3,
    "LNG": 31,
    "BIG": 30,
    "100+": 0,
    "STUFF": 1,
    "FUM": 6,
    "FUML": 0,
    "1ST": 35,
    "PCT": "36.80%"
  },
  
    "McKinnon, Jerick": {
    "GP": 16,
    "ATT": 150,
    "ATT/G": 9.4,
    "YDS": 59,
    "AVG": 3.8,
    "YDS/G": 35.6,
    "TD": 3,
    "LNG": 58,
    "BIG": 12,
    "100+": 0,
    "STUFF": 23,
    "FUM": 2,
    "FUML": 2,
    "1ST": 23,
    "PCT": "15.30%"
  },
  
    "Williams, Jamaal": {
    "GP": 16,
    "ATT": 153,
    "ATT/G": 9.6,
    "YDS": 10,
    "AVG": 3.6,
    "YDS/G": 34.8,
    "TD": 4,
    "LNG": 25,
    "BIG": 6,
    "100+": 1,
    "STUFF": 6,
    "FUM": 0,
    "FUML": 0,
    "1ST": 32,
    "PCT": "20.90%"
  },
  
    "Abdullah, Ameer": {
    "GP": 14,
    "ATT": 165,
    "ATT/G": 11.8,
    "YDS": 63,
    "AVG": 3.4,
    "YDS/G": 39.4,
    "TD": 4,
    "LNG": 34,
    "BIG": 13,
    "100+": 0,
    "STUFF": 30,
    "FUM": 2,
    "FUML": 1,
    "1ST": 24,
    "PCT": "14.50%"
  },
  
    "Morris, Alfred": {
    "GP": 14,
    "ATT": 115,
    "ATT/G": 8.2,
    "YDS": 22,
    "AVG": 4.8,
    "YDS/G": 39.1,
    "TD": 1,
    "LNG": 70,
    "BIG": 13,
    "100+": 1,
    "STUFF": 12,
    "FUM": 0,
    "FUML": 0,
    "1ST": 25,
    "PCT": "21.70%"
  },
  
    "Peterson, Adrian": {
    "GP": 10,
    "ATT": 156,
    "ATT/G": 15.6,
    "YDS": 47,
    "AVG": 3.4,
    "YDS/G": 52.9,
    "TD": 2,
    "LNG": 27,
    "BIG": 10,
    "100+": 2,
    "STUFF": 23,
    "FUM": 3,
    "FUML": 2,
    "1ST": 20,
    "PCT": "12.80%"
  },
  
    "Gallman, Wayne": {
    "GP": 13,
    "ATT": 111,
    "ATT/G": 8.5,
    "YDS": 22,
    "AVG": 4.3,
    "YDS/G": 36.6,
    "TD": 0,
    "LNG": 24,
    "BIG": 10,
    "100+": 0,
    "STUFF": 9,
    "FUM": 3,
    "FUML": 1,
    "1ST": 19,
    "PCT": "17.10%"
  },
  
    "Breida, Matt": {
    "GP": 16,
    "ATT": 105,
    "ATT/G": 6.6,
    "YDS": 23,
    "AVG": 4.4,
    "YDS/G": 29.1,
    "TD": 2,
    "LNG": 33,
    "BIG": 17,
    "100+": 0,
    "STUFF": 10,
    "FUM": 1,
    "FUML": 0,
    "1ST": 22,
    "PCT": "21.00%"
  },
  
    "Bernard, Giovani": {
    "GP": 16,
    "ATT": 105,
    "ATT/G": 6.6,
    "YDS": 24,
    "AVG": 4.4,
    "YDS/G": 28.6,
    "TD": 2,
    "LNG": 25,
    "BIG": 14,
    "100+": 1,
    "STUFF": 11,
    "FUM": 0,
    "FUML": 0,
    "1ST": 20,
    "PCT": "19.00%"
  },
  
    "Jones, Aaron": {
    "GP": 12,
    "ATT": 81,
    "ATT/G": 6.8,
    "YDS": 8,
    "AVG": 5.5,
    "YDS/G": 37.3,
    "TD": 4,
    "LNG": 46,
    "BIG": 12,
    "100+": 2,
    "STUFF": 6,
    "FUM": 0,
    "FUML": 0,
    "1ST": 21,
    "PCT": "25.90%"
  },
  
    "McCaffrey, Christian": {
    "GP": 16,
    "ATT": 117,
    "ATT/G": 7.3,
    "YDS": 38,
    "AVG": 3.7,
    "YDS/G": 27.2,
    "TD": 2,
    "LNG": 40,
    "BIG": 8,
    "100+": 0,
    "STUFF": 13,
    "FUM": 1,
    "FUML": 1,
    "1ST": 21,
    "PCT": "17.90%"
  },
  
    "Taylor, Tyrod": {
    "GP": 15,
    "ATT": 84,
    "ATT/G": 5.6,
    "YDS": 6,
    "AVG": 5.1,
    "YDS/G": 28.5,
    "TD": 4,
    "LNG": 32,
    "BIG": 15,
    "100+": 0,
    "STUFF": 2,
    "FUM": 1,
    "FUML": 0,
    "1ST": 26,
    "PCT": "31.00%"
  },
  
    "Williams, Kerwynn": {
    "GP": 16,
    "ATT": 120,
    "ATT/G": 7.5,
    "YDS": 21,
    "AVG": 3.6,
    "YDS/G": 26.6,
    "TD": 1,
    "LNG": 25,
    "BIG": 7,
    "100+": 0,
    "STUFF": 10,
    "FUM": 0,
    "FUML": 0,
    "1ST": 20,
    "PCT": "16.70%"
  },
  
    "Barber, Peyton": {
    "GP": 16,
    "ATT": 108,
    "ATT/G": 6.8,
    "YDS": 13,
    "AVG": 3.9,
    "YDS/G": 26.4,
    "TD": 3,
    "LNG": 34,
    "BIG": 4,
    "100+": 1,
    "STUFF": 6,
    "FUM": 2,
    "FUML": 1,
    "1ST": 23,
    "PCT": "21.30%"
  },
  
    "Kizer, DeShone": {
    "GP": 15,
    "ATT": 77,
    "ATT/G": 5.1,
    "YDS": 4,
    "AVG": 5.4,
    "YDS/G": 27.9,
    "TD": 5,
    "LNG": 20,
    "BIG": 13,
    "100+": 0,
    "STUFF": 1,
    "FUM": 3,
    "FUML": 1,
    "1ST": 28,
    "PCT": "36.40%"
  },
  
    "Martin, Doug": {
    "GP": 11,
    "ATT": 138,
    "ATT/G": 12.5,
    "YDS": 46,
    "AVG": 2.9,
    "YDS/G": 36.9,
    "TD": 3,
    "LNG": 27,
    "BIG": 9,
    "100+": 0,
    "STUFF": 20,
    "FUM": 1,
    "FUML": 1,
    "1ST": 21,
    "PCT": "15.20%"
  },
  
    "Gillislee, Mike": {
    "GP": 9,
    "ATT": 104,
    "ATT/G": 11.6,
    "YDS": 18,
    "AVG": 3.7,
    "YDS/G": 42.6,
    "TD": 5,
    "LNG": 16,
    "BIG": 5,
    "100+": 0,
    "STUFF": 8,
    "FUM": 1,
    "FUML": 1,
    "1ST": 25,
    "PCT": "24.00%"
  },
  
    "Ivory, Chris": {
    "GP": 14,
    "ATT": 112,
    "ATT/G": 8,
    "YDS": 16,
    "AVG": 3.4,
    "YDS/G": 27.3,
    "TD": 1,
    "LNG": 34,
    "BIG": 7,
    "100+": 0,
    "STUFF": 6,
    "FUM": 2,
    "FUML": 2,
    "1ST": 16,
    "PCT": "14.30%"
  },
  
    "Forte, Matt": {
    "GP": 12,
    "ATT": 103,
    "ATT/G": 8.6,
    "YDS": 13,
    "AVG": 3.7,
    "YDS/G": 31.8,
    "TD": 2,
    "LNG": 20,
    "BIG": 9,
    "100+": 0,
    "STUFF": 9,
    "FUM": 1,
    "FUML": 1,
    "1ST": 12,
    "PCT": "11.70%"
  },
  
    "Cohen, Tarik": {
    "GP": 16,
    "ATT": 87,
    "ATT/G": 5.4,
    "YDS": 70,
    "AVG": 4.3,
    "YDS/G": 23.1,
    "TD": 2,
    "LNG": 46,
    "BIG": 11,
    "100+": 0,
    "STUFF": 23,
    "FUM": 2,
    "FUML": 1,
    "1ST": 17,
    "PCT": "19.50%"
  },
  
    "Mack, Marlon": {
    "GP": 14,
    "ATT": 93,
    "ATT/G": 6.6,
    "YDS": 52,
    "AVG": 3.9,
    "YDS/G": 25.6,
    "TD": 3,
    "LNG": 35,
    "BIG": 12,
    "100+": 0,
    "STUFF": 19,
    "FUM": 1,
    "FUML": 0,
    "1ST": 21,
    "PCT": "22.60%"
  },
  
    "Prescott, Dak": {
    "GP": 16,
    "ATT": 57,
    "ATT/G": 3.6,
    "YDS": 0,
    "AVG": 6.3,
    "YDS/G": 22.3,
    "TD": 6,
    "LNG": 21,
    "BIG": 19,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 29,
    "PCT": "50.90%"
  },
  
    "Smith, Alex": {
    "GP": 15,
    "ATT": 60,
    "ATT/G": 4,
    "YDS": 1,
    "AVG": 5.9,
    "YDS/G": 23.7,
    "TD": 1,
    "LNG": 70,
    "BIG": 11,
    "100+": 0,
    "STUFF": 1,
    "FUM": 2,
    "FUML": 0,
    "1ST": 19,
    "PCT": "31.70%"
  },
  
    "Cook, Dalvin": {
    "GP": 4,
    "ATT": 74,
    "ATT/G": 18.5,
    "YDS": 11,
    "AVG": 4.8,
    "YDS/G": 88.5,
    "TD": 2,
    "LNG": 33,
    "BIG": 8,
    "100+": 1,
    "STUFF": 5,
    "FUM": 1,
    "FUML": 1,
    "1ST": 15,
    "PCT": "20.30%"
  },
  
    "Johnson Jr., Duke": {
    "GP": 16,
    "ATT": 82,
    "ATT/G": 5.1,
    "YDS": 21,
    "AVG": 4.2,
    "YDS/G": 21.8,
    "TD": 4,
    "LNG": 19,
    "BIG": 12,
    "100+": 0,
    "STUFF": 9,
    "FUM": 1,
    "FUML": 0,
    "1ST": 26,
    "PCT": "31.70%"
  },
  
    "Foreman, D'Onta": {
    "GP": 10,
    "ATT": 78,
    "ATT/G": 7.8,
    "YDS": 13,
    "AVG": 4.2,
    "YDS/G": 32.7,
    "TD": 2,
    "LNG": 39,
    "BIG": 5,
    "100+": 0,
    "STUFF": 7,
    "FUM": 2,
    "FUML": 1,
    "1ST": 13,
    "PCT": "16.70%"
  },
  
    "Bortles, Blake": {
    "GP": 16,
    "ATT": 57,
    "ATT/G": 3.6,
    "YDS": 0,
    "AVG": 5.7,
    "YDS/G": 20.1,
    "TD": 2,
    "LNG": 28,
    "BIG": 10,
    "100+": 0,
    "STUFF": 0,
    "FUM": 3,
    "FUML": 0,
    "1ST": 19,
    "PCT": "33.30%"
  },
  
    "Clement, Corey": {
    "GP": 16,
    "ATT": 74,
    "ATT/G": 4.6,
    "YDS": 22,
    "AVG": 4.3,
    "YDS/G": 20.1,
    "TD": 4,
    "LNG": 28,
    "BIG": 10,
    "100+": 0,
    "STUFF": 11,
    "FUM": 0,
    "FUML": 0,
    "1ST": 19,
    "PCT": "25.70%"
  },
  
    "McGuire, Elijah": {
    "GP": 16,
    "ATT": 88,
    "ATT/G": 5.5,
    "YDS": 37,
    "AVG": 3.6,
    "YDS/G": 19.7,
    "TD": 1,
    "LNG": 69,
    "BIG": 8,
    "100+": 0,
    "STUFF": 18,
    "FUM": 1,
    "FUML": 1,
    "1ST": 14,
    "PCT": "15.90%"
  },
  
    "Mariota, Marcus": {
    "GP": 15,
    "ATT": 60,
    "ATT/G": 4,
    "YDS": 2,
    "AVG": 5.2,
    "YDS/G": 20.8,
    "TD": 5,
    "LNG": 34,
    "BIG": 9,
    "100+": 0,
    "STUFF": 1,
    "FUM": 2,
    "FUML": 1,
    "1ST": 22,
    "PCT": "36.70%"
  },
  
    "Wentz, Carson": {
    "GP": 13,
    "ATT": 64,
    "ATT/G": 4.9,
    "YDS": 0,
    "AVG": 4.7,
    "YDS/G": 23,
    "TD": 0,
    "LNG": 24,
    "BIG": 12,
    "100+": 0,
    "STUFF": 0,
    "FUM": 5,
    "FUML": 2,
    "1ST": 26,
    "PCT": "40.60%"
  },
  
    "Booker, Devontae": {
    "GP": 13,
    "ATT": 79,
    "ATT/G": 6.1,
    "YDS": 9,
    "AVG": 3.8,
    "YDS/G": 23,
    "TD": 1,
    "LNG": 26,
    "BIG": 5,
    "100+": 0,
    "STUFF": 7,
    "FUM": 1,
    "FUML": 0,
    "1ST": 11,
    "PCT": "13.90%"
  },
  
    "Charles, Jamaal": {
    "GP": 14,
    "ATT": 69,
    "ATT/G": 4.9,
    "YDS": 13,
    "AVG": 4.3,
    "YDS/G": 21.1,
    "TD": 1,
    "LNG": 19,
    "BIG": 10,
    "100+": 0,
    "STUFF": 7,
    "FUM": 2,
    "FUML": 2,
    "1ST": 16,
    "PCT": "23.20%"
  },
  
    "Thompson, Chris": {
    "GP": 10,
    "ATT": 64,
    "ATT/G": 6.4,
    "YDS": 25,
    "AVG": 4.6,
    "YDS/G": 29.4,
    "TD": 2,
    "LNG": 61,
    "BIG": 8,
    "100+": 0,
    "STUFF": 11,
    "FUM": 1,
    "FUML": 0,
    "1ST": 11,
    "PCT": "17.20%"
  },
  
    "Riddick, Theo": {
    "GP": 16,
    "ATT": 84,
    "ATT/G": 5.3,
    "YDS": 33,
    "AVG": 3.4,
    "YDS/G": 17.9,
    "TD": 3,
    "LNG": 21,
    "BIG": 9,
    "100+": 0,
    "STUFF": 14,
    "FUM": 1,
    "FUML": 1,
    "1ST": 11,
    "PCT": "13.10%"
  },
  
    "Richard, Jalen": {
    "GP": 16,
    "ATT": 56,
    "ATT/G": 3.5,
    "YDS": 20,
    "AVG": 4.9,
    "YDS/G": 17.2,
    "TD": 1,
    "LNG": 52,
    "BIG": 6,
    "100+": 0,
    "STUFF": 8,
    "FUM": 1,
    "FUML": 1,
    "1ST": 10,
    "PCT": "17.90%"
  },
  
    "Montgomery, Ty": {
    "GP": 8,
    "ATT": 71,
    "ATT/G": 8.9,
    "YDS": 7,
    "AVG": 3.9,
    "YDS/G": 34.1,
    "TD": 3,
    "LNG": 37,
    "BIG": 2,
    "100+": 0,
    "STUFF": 4,
    "FUM": 0,
    "FUML": 0,
    "1ST": 13,
    "PCT": "18.30%"
  },
  
    "Austin, Tavon": {
    "GP": 16,
    "ATT": 59,
    "ATT/G": 3.7,
    "YDS": 32,
    "AVG": 4.6,
    "YDS/G": 16.9,
    "TD": 1,
    "LNG": 27,
    "BIG": 8,
    "100+": 0,
    "STUFF": 9,
    "FUM": 0,
    "FUML": 0,
    "1ST": 9,
    "PCT": "15.30%"
  },
  
    "Hundley, Brett": {
    "GP": 11,
    "ATT": 36,
    "ATT/G": 3.3,
    "YDS": 4,
    "AVG": 7.5,
    "YDS/G": 24.5,
    "TD": 2,
    "LNG": 24,
    "BIG": 12,
    "100+": 0,
    "STUFF": 2,
    "FUM": 2,
    "FUML": 1,
    "1ST": 21,
    "PCT": "58.30%"
  },
  
    "Watson, Deshaun": {
    "GP": 7,
    "ATT": 36,
    "ATT/G": 5.1,
    "YDS": 0,
    "AVG": 7.5,
    "YDS/G": 38.4,
    "TD": 2,
    "LNG": 49,
    "BIG": 7,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 14,
    "PCT": "38.90%"
  },
  
    "Burkhead, Rex": {
    "GP": 10,
    "ATT": 64,
    "ATT/G": 6.4,
    "YDS": 6,
    "AVG": 4.1,
    "YDS/G": 26.4,
    "TD": 5,
    "LNG": 31,
    "BIG": 5,
    "100+": 0,
    "STUFF": 4,
    "FUM": 1,
    "FUML": 0,
    "1ST": 14,
    "PCT": "21.90%"
  },
  
    "Blue, Alfred": {
    "GP": 11,
    "ATT": 71,
    "ATT/G": 6.5,
    "YDS": 12,
    "AVG": 3.7,
    "YDS/G": 23.8,
    "TD": 1,
    "LNG": 48,
    "BIG": 2,
    "100+": 1,
    "STUFF": 6,
    "FUM": 0,
    "FUML": 0,
    "1ST": 10,
    "PCT": "14.10%"
  },
  
    "Brissett, Jacoby": {
    "GP": 16,
    "ATT": 63,
    "ATT/G": 3.9,
    "YDS": 8,
    "AVG": 4.1,
    "YDS/G": 16.3,
    "TD": 4,
    "LNG": 25,
    "BIG": 9,
    "100+": 0,
    "STUFF": 2,
    "FUM": 3,
    "FUML": 1,
    "1ST": 14,
    "PCT": "22.20%"
  },
  
    "Ekeler, Austin": {
    "GP": 16,
    "ATT": 47,
    "ATT/G": 2.9,
    "YDS": 11,
    "AVG": 5.5,
    "YDS/G": 16.3,
    "TD": 2,
    "LNG": 35,
    "BIG": 7,
    "100+": 0,
    "STUFF": 5,
    "FUM": 1,
    "FUML": 1,
    "1ST": 12,
    "PCT": "25.50%"
  },
  
    "Yeldon, T.J.": {
    "GP": 10,
    "ATT": 49,
    "ATT/G": 4.9,
    "YDS": 12,
    "AVG": 5.2,
    "YDS/G": 25.3,
    "TD": 2,
    "LNG": 58,
    "BIG": 5,
    "100+": 1,
    "STUFF": 3,
    "FUM": 2,
    "FUML": 1,
    "1ST": 7,
    "PCT": "14.30%"
  },
  
    "Grant, Corey": {
    "GP": 16,
    "ATT": 30,
    "ATT/G": 1.9,
    "YDS": 10,
    "AVG": 8.3,
    "YDS/G": 15.5,
    "TD": 2,
    "LNG": 58,
    "BIG": 7,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 10,
    "PCT": "33.30%"
  },
  
    "Trubisky, Mitchell": {
    "GP": 12,
    "ATT": 41,
    "ATT/G": 3.4,
    "YDS": 2,
    "AVG": 6.1,
    "YDS/G": 20.7,
    "TD": 2,
    "LNG": 46,
    "BIG": 9,
    "100+": 0,
    "STUFF": 1,
    "FUM": 5,
    "FUML": 1,
    "1ST": 12,
    "PCT": "29.30%"
  },
  
    "Tolbert, Mike": {
    "GP": 12,
    "ATT": 66,
    "ATT/G": 5.5,
    "YDS": 13,
    "AVG": 3.7,
    "YDS/G": 20.6,
    "TD": 1,
    "LNG": 25,
    "BIG": 6,
    "100+": 0,
    "STUFF": 6,
    "FUM": 2,
    "FUML": 1,
    "1ST": 9,
    "PCT": "13.60%"
  },
  
    "Brown, Malcolm": {
    "GP": 11,
    "ATT": 63,
    "ATT/G": 5.7,
    "YDS": 6,
    "AVG": 3.9,
    "YDS/G": 22.4,
    "TD": 1,
    "LNG": 20,
    "BIG": 8,
    "100+": 0,
    "STUFF": 3,
    "FUM": 1,
    "FUML": 0,
    "1ST": 10,
    "PCT": "15.90%"
  },
  
    "Rodgers, Jacquizz": {
    "GP": 16,
    "ATT": 64,
    "ATT/G": 4,
    "YDS": 5,
    "AVG": 3.8,
    "YDS/G": 15.3,
    "TD": 1,
    "LNG": 36,
    "BIG": 4,
    "100+": 0,
    "STUFF": 5,
    "FUM": 0,
    "FUML": 0,
    "1ST": 11,
    "PCT": "17.20%"
  },
  
    "Davis, Mike": {
    "GP": 6,
    "ATT": 68,
    "ATT/G": 11.3,
    "YDS": 35,
    "AVG": 3.5,
    "YDS/G": 40,
    "TD": 0,
    "LNG": 33,
    "BIG": 10,
    "100+": 0,
    "STUFF": 16,
    "FUM": 0,
    "FUML": 0,
    "1ST": 12,
    "PCT": "17.60%"
  },
  
    "Smith, Rod": {
    "GP": 15,
    "ATT": 55,
    "ATT/G": 3.7,
    "YDS": 11,
    "AVG": 4.2,
    "YDS/G": 15.5,
    "TD": 4,
    "LNG": 45,
    "BIG": 4,
    "100+": 0,
    "STUFF": 5,
    "FUM": 0,
    "FUML": 0,
    "1ST": 15,
    "PCT": "27.30%"
  },
  
    "Carson, Chris": {
    "GP": 4,
    "ATT": 49,
    "ATT/G": 12.3,
    "YDS": 3,
    "AVG": 4.2,
    "YDS/G": 52,
    "TD": 0,
    "LNG": 30,
    "BIG": 6,
    "100+": 0,
    "STUFF": 3,
    "FUM": 0,
    "FUML": 0,
    "1ST": 11,
    "PCT": "22.40%"
  },
  
    "Kelley, Rob": {
    "GP": 7,
    "ATT": 62,
    "ATT/G": 8.9,
    "YDS": 25,
    "AVG": 3.1,
    "YDS/G": 27.7,
    "TD": 3,
    "LNG": 21,
    "BIG": 4,
    "100+": 0,
    "STUFF": 11,
    "FUM": 0,
    "FUML": 0,
    "1ST": 8,
    "PCT": "12.90%"
  },
  
    "McKissic, J.D.": {
    "GP": 13,
    "ATT": 46,
    "ATT/G": 3.5,
    "YDS": 18,
    "AVG": 4.1,
    "YDS/G": 14.4,
    "TD": 1,
    "LNG": 30,
    "BIG": 5,
    "100+": 0,
    "STUFF": 8,
    "FUM": 0,
    "FUML": 0,
    "1ST": 8,
    "PCT": "17.40%"
  },
  
    "Williams, Damien": {
    "GP": 11,
    "ATT": 46,
    "ATT/G": 4.2,
    "YDS": 16,
    "AVG": 3.9,
    "YDS/G": 16.5,
    "TD": 0,
    "LNG": 69,
    "BIG": 3,
    "100+": 0,
    "STUFF": 7,
    "FUM": 0,
    "FUML": 0,
    "1ST": 7,
    "PCT": "15.20%"
  },
  
    "Cousins, Kirk": {
    "GP": 16,
    "ATT": 49,
    "ATT/G": 3.1,
    "YDS": 1,
    "AVG": 3.7,
    "YDS/G": 11.2,
    "TD": 4,
    "LNG": 18,
    "BIG": 6,
    "100+": 0,
    "STUFF": 1,
    "FUM": 7,
    "FUML": 1,
    "1ST": 17,
    "PCT": "34.70%"
  },
  
    "Lacy, Eddie": {
    "GP": 9,
    "ATT": 69,
    "ATT/G": 7.7,
    "YDS": 23,
    "AVG": 2.6,
    "YDS/G": 19.9,
    "TD": 0,
    "LNG": 19,
    "BIG": 4,
    "100+": 0,
    "STUFF": 9,
    "FUM": 0,
    "FUML": 0,
    "1ST": 7,
    "PCT": "10.10%"
  },
  
    "Smallwood, Wendell": {
    "GP": 8,
    "ATT": 47,
    "ATT/G": 5.9,
    "YDS": 19,
    "AVG": 3.7,
    "YDS/G": 21.8,
    "TD": 1,
    "LNG": 26,
    "BIG": 4,
    "100+": 0,
    "STUFF": 7,
    "FUM": 0,
    "FUML": 0,
    "1ST": 9,
    "PCT": "19.10%"
  },
  
    "White, James": {
    "GP": 14,
    "ATT": 43,
    "ATT/G": 3.1,
    "YDS": 9,
    "AVG": 4,
    "YDS/G": 12.2,
    "TD": 0,
    "LNG": 10,
    "BIG": 1,
    "100+": 0,
    "STUFF": 3,
    "FUM": 0,
    "FUML": 0,
    "1ST": 6,
    "PCT": "14.00%"
  },
  
    "Green, Tion": {
    "GP": 5,
    "ATT": 42,
    "ATT/G": 8.4,
    "YDS": 4,
    "AVG": 3.9,
    "YDS/G": 33,
    "TD": 2,
    "LNG": 33,
    "BIG": 4,
    "100+": 0,
    "STUFF": 3,
    "FUM": 0,
    "FUML": 0,
    "1ST": 9,
    "PCT": "21.40%"
  },
  
    "Vereen, Shane": {
    "GP": 16,
    "ATT": 45,
    "ATT/G": 2.8,
    "YDS": 20,
    "AVG": 3.6,
    "YDS/G": 10.3,
    "TD": 0,
    "LNG": 17,
    "BIG": 3,
    "100+": 0,
    "STUFF": 6,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "6.70%"
  },
  
    "Keenum, Case": {
    "GP": 15,
    "ATT": 40,
    "ATT/G": 2.7,
    "YDS": 0,
    "AVG": 4,
    "YDS/G": 10.7,
    "TD": 1,
    "LNG": 22,
    "BIG": 7,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 13,
    "PCT": "32.50%"
  },
  
    "Rawls, Thomas": {
    "GP": 12,
    "ATT": 58,
    "ATT/G": 4.8,
    "YDS": 22,
    "AVG": 2.7,
    "YDS/G": 13.1,
    "TD": 0,
    "LNG": 23,
    "BIG": 3,
    "100+": 0,
    "STUFF": 9,
    "FUM": 1,
    "FUML": 1,
    "1ST": 6,
    "PCT": "10.30%"
  },
  
    "Washington, DeAndre": {
    "GP": 15,
    "ATT": 57,
    "ATT/G": 3.8,
    "YDS": 20,
    "AVG": 2.7,
    "YDS/G": 10.2,
    "TD": 2,
    "LNG": 11,
    "BIG": 5,
    "100+": 0,
    "STUFF": 8,
    "FUM": 1,
    "FUML": 0,
    "1ST": 9,
    "PCT": "15.80%"
  },
  
    "Conner, James": {
    "GP": 14,
    "ATT": 32,
    "ATT/G": 2.3,
    "YDS": 8,
    "AVG": 4.5,
    "YDS/G": 10.3,
    "TD": 0,
    "LNG": 23,
    "BIG": 6,
    "100+": 0,
    "STUFF": 4,
    "FUM": 0,
    "FUML": 0,
    "1ST": 4,
    "PCT": "12.50%"
  },
  
    "Ryan, Matt": {
    "GP": 16,
    "ATT": 32,
    "ATT/G": 2,
    "YDS": 0,
    "AVG": 4.5,
    "YDS/G": 8.9,
    "TD": 0,
    "LNG": 16,
    "BIG": 7,
    "100+": 0,
    "STUFF": 0,
    "FUM": 3,
    "FUML": 2,
    "1ST": 11,
    "PCT": "34.40%"
  },
  
    "West, Terrance": {
    "GP": 5,
    "ATT": 39,
    "ATT/G": 7.8,
    "YDS": 15,
    "AVG": 3.5,
    "YDS/G": 27.6,
    "TD": 2,
    "LNG": 13,
    "BIG": 5,
    "100+": 0,
    "STUFF": 6,
    "FUM": 1,
    "FUML": 1,
    "1ST": 11,
    "PCT": "28.20%"
  },
  
    "Beathard, C.J.": {
    "GP": 7,
    "ATT": 26,
    "ATT/G": 3.7,
    "YDS": 1,
    "AVG": 5.2,
    "YDS/G": 19.4,
    "TD": 3,
    "LNG": 16,
    "BIG": 4,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 9,
    "PCT": "34.60%"
  },
  
    "Winston, Jameis": {
    "GP": 13,
    "ATT": 33,
    "ATT/G": 2.5,
    "YDS": 0,
    "AVG": 4.1,
    "YDS/G": 10.4,
    "TD": 1,
    "LNG": 17,
    "BIG": 4,
    "100+": 0,
    "STUFF": 0,
    "FUM": 4,
    "FUML": 1,
    "1ST": 7,
    "PCT": "21.20%"
  },
  
    "Ward, Terron": {
    "GP": 14,
    "ATT": 30,
    "ATT/G": 2.1,
    "YDS": 8,
    "AVG": 4.3,
    "YDS/G": 9.2,
    "TD": 0,
    "LNG": 17,
    "BIG": 4,
    "100+": 0,
    "STUFF": 6,
    "FUM": 1,
    "FUML": 1,
    "1ST": 7,
    "PCT": "23.30%"
  },
  
    "Siemian, Trevor": {
    "GP": 11,
    "ATT": 31,
    "ATT/G": 2.8,
    "YDS": 0,
    "AVG": 4.1,
    "YDS/G": 11.5,
    "TD": 1,
    "LNG": 15,
    "BIG": 2,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 8,
    "PCT": "25.80%"
  },
  
    "Rodgers, Aaron": {
    "GP": 7,
    "ATT": 24,
    "ATT/G": 3.4,
    "YDS": 2,
    "AVG": 5.3,
    "YDS/G": 18,
    "TD": 0,
    "LNG": 18,
    "BIG": 4,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 10,
    "PCT": "41.70%"
  },
  
    "McCown, Josh": {
    "GP": 13,
    "ATT": 37,
    "ATT/G": 2.8,
    "YDS": 0,
    "AVG": 3.4,
    "YDS/G": 9.5,
    "TD": 5,
    "LNG": 22,
    "BIG": 5,
    "100+": 0,
    "STUFF": 0,
    "FUM": 4,
    "FUML": 1,
    "1ST": 14,
    "PCT": "37.80%"
  },
  
    "Penny, Elijhaa": {
    "GP": 16,
    "ATT": 31,
    "ATT/G": 1.9,
    "YDS": 4,
    "AVG": 4,
    "YDS/G": 7.8,
    "TD": 2,
    "LNG": 14,
    "BIG": 2,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 7,
    "PCT": "22.60%"
  },
  
    "Patterson, Cordarrelle": {
    "GP": 16,
    "ATT": 13,
    "ATT/G": 0.8,
    "YDS": 7,
    "AVG": 9.3,
    "YDS/G": 7.6,
    "TD": 2,
    "LNG": 47,
    "BIG": 2,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "23.10%"
  },
  
    "Hill, Jeremy": {
    "GP": 7,
    "ATT": 37,
    "ATT/G": 5.3,
    "YDS": 8,
    "AVG": 3.1,
    "YDS/G": 16.6,
    "TD": 0,
    "LNG": 13,
    "BIG": 3,
    "100+": 0,
    "STUFF": 4,
    "FUM": 1,
    "FUML": 0,
    "1ST": 5,
    "PCT": "13.50%"
  },
  
    "Johnson, Chris": {
    "GP": 4,
    "ATT": 45,
    "ATT/G": 11.3,
    "YDS": 15,
    "AVG": 2.5,
    "YDS/G": 28.5,
    "TD": 0,
    "LNG": 11,
    "BIG": 1,
    "100+": 0,
    "STUFF": 8,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "6.70%"
  },
  
    "Ridley, Stevan": {
    "GP": 2,
    "ATT": 26,
    "ATT/G": 13,
    "YDS": 7,
    "AVG": 4.2,
    "YDS/G": 54,
    "TD": 1,
    "LNG": 21,
    "BIG": 4,
    "100+": 0,
    "STUFF": 3,
    "FUM": 0,
    "FUML": 0,
    "1ST": 6,
    "PCT": "23.10%"
  },
  
    "Dalton, Andy": {
    "GP": 16,
    "ATT": 38,
    "ATT/G": 2.4,
    "YDS": 1,
    "AVG": 2.6,
    "YDS/G": 6.2,
    "TD": 0,
    "LNG": 25,
    "BIG": 5,
    "100+": 0,
    "STUFF": 1,
    "FUM": 1,
    "FUML": 1,
    "1ST": 9,
    "PCT": "23.70%"
  },
  
    "Stafford, Matthew": {
    "GP": 16,
    "ATT": 29,
    "ATT/G": 1.8,
    "YDS": 0,
    "AVG": 3.4,
    "YDS/G": 6.1,
    "TD": 0,
    "LNG": 15,
    "BIG": 5,
    "100+": 0,
    "STUFF": 0,
    "FUM": 2,
    "FUML": 1,
    "1ST": 9,
    "PCT": "31.00%"
  },
  
    "Benjamin, Travis": {
    "GP": 16,
    "ATT": 13,
    "ATT/G": 0.8,
    "YDS": 4,
    "AVG": 7.4,
    "YDS/G": 6,
    "TD": 0,
    "LNG": 22,
    "BIG": 3,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 5,
    "PCT": "38.50%"
  },
  
    "Cadet, Travaris": {
    "GP": 9,
    "ATT": 23,
    "ATT/G": 2.6,
    "YDS": 3,
    "AVG": 4.2,
    "YDS/G": 10.7,
    "TD": 0,
    "LNG": 12,
    "BIG": 3,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 6,
    "PCT": "26.10%"
  },
  
    "Sims, Charles": {
    "GP": 16,
    "ATT": 21,
    "ATT/G": 1.3,
    "YDS": 1,
    "AVG": 4.5,
    "YDS/G": 5.9,
    "TD": 0,
    "LNG": 21,
    "BIG": 3,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 6,
    "PCT": "28.60%"
  },
  
    "Artis-Payne, Cameron": {
    "GP": 13,
    "ATT": 18,
    "ATT/G": 1.4,
    "YDS": 6,
    "AVG": 5.3,
    "YDS/G": 7.3,
    "TD": 1,
    "LNG": 43,
    "BIG": 4,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 5,
    "PCT": "27.80%"
  },
  
    "Perkins, Paul": {
    "GP": 11,
    "ATT": 41,
    "ATT/G": 3.7,
    "YDS": 13,
    "AVG": 2.2,
    "YDS/G": 8.2,
    "TD": 0,
    "LNG": 14,
    "BIG": 1,
    "100+": 0,
    "STUFF": 6,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "7.30%"
  },
  
    "Oliver, Branden": {
    "GP": 8,
    "ATT": 35,
    "ATT/G": 4.4,
    "YDS": 20,
    "AVG": 2.4,
    "YDS/G": 10.4,
    "TD": 0,
    "LNG": 26,
    "BIG": 2,
    "100+": 0,
    "STUFF": 7,
    "FUM": 0,
    "FUML": 0,
    "1ST": 6,
    "PCT": "17.10%"
  },
  
    "Gabbert, Blaine": {
    "GP": 5,
    "ATT": 22,
    "ATT/G": 4.4,
    "YDS": 0,
    "AVG": 3.7,
    "YDS/G": 16.4,
    "TD": 0,
    "LNG": 12,
    "BIG": 3,
    "100+": 0,
    "STUFF": 0,
    "FUM": 3,
    "FUML": 0,
    "1ST": 7,
    "PCT": "31.80%"
  },
  
    "Bibbs, Kapri": {
    "GP": 3,
    "ATT": 21,
    "ATT/G": 7,
    "YDS": 1,
    "AVG": 3.8,
    "YDS/G": 26.3,
    "TD": 0,
    "LNG": 16,
    "BIG": 2,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 4,
    "PCT": "19.00%"
  },
  
    "Fitzpatrick, Ryan": {
    "GP": 6,
    "ATT": 15,
    "ATT/G": 2.5,
    "YDS": 0,
    "AVG": 5.2,
    "YDS/G": 13,
    "TD": 0,
    "LNG": 15,
    "BIG": 4,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 5,
    "PCT": "33.30%"
  },
  
    "West, Charcandrick": {
    "GP": 13,
    "ATT": 18,
    "ATT/G": 1.4,
    "YDS": 3,
    "AVG": 4,
    "YDS/G": 5.5,
    "TD": 2,
    "LNG": 21,
    "BIG": 2,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 4,
    "PCT": "22.20%"
  },
  
    "Hogan, Kevin": {
    "GP": 4,
    "ATT": 10,
    "ATT/G": 2.5,
    "YDS": 0,
    "AVG": 7.1,
    "YDS/G": 17.8,
    "TD": 0,
    "LNG": 11,
    "BIG": 3,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 4,
    "PCT": "40.00%"
  },
  
    "Bolden, Brandon": {
    "GP": 16,
    "ATT": 13,
    "ATT/G": 0.8,
    "YDS": 1,
    "AVG": 5.2,
    "YDS/G": 4.2,
    "TD": 0,
    "LNG": 20,
    "BIG": 2,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "23.10%"
  },
  
    "Carr, Derek": {
    "GP": 15,
    "ATT": 23,
    "ATT/G": 1.5,
    "YDS": 1,
    "AVG": 2.9,
    "YDS/G": 4.4,
    "TD": 0,
    "LNG": 32,
    "BIG": 2,
    "100+": 0,
    "STUFF": 1,
    "FUM": 4,
    "FUML": 2,
    "1ST": 5,
    "PCT": "21.70%"
  },
  
    "Osweiler, Brock": {
    "GP": 6,
    "ATT": 14,
    "ATT/G": 2.3,
    "YDS": 2,
    "AVG": 4.6,
    "YDS/G": 10.7,
    "TD": 1,
    "LNG": 18,
    "BIG": 3,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "21.40%"
  },
  
    "Samuel, Curtis": {
    "GP": 9,
    "ATT": 4,
    "ATT/G": 0.4,
    "YDS": 0,
    "AVG": 16,
    "YDS/G": 7.1,
    "TD": 0,
    "LNG": 31,
    "BIG": 3,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "75.00%"
  },
  
    "Sproles, Darren": {
    "GP": 3,
    "ATT": 15,
    "ATT/G": 5,
    "YDS": 4,
    "AVG": 4.1,
    "YDS/G": 20.3,
    "TD": 0,
    "LNG": 12,
    "BIG": 3,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 4,
    "PCT": "26.70%"
  },
  
    "Hill, Tyreek": {
    "GP": 15,
    "ATT": 17,
    "ATT/G": 1.1,
    "YDS": 18,
    "AVG": 3.5,
    "YDS/G": 3.9,
    "TD": 0,
    "LNG": 16,
    "BIG": 3,
    "100+": 0,
    "STUFF": 4,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "17.60%"
  },
  
    "Lockett, Tyler": {
    "GP": 16,
    "ATT": 10,
    "ATT/G": 0.6,
    "YDS": 2,
    "AVG": 5.8,
    "YDS/G": 3.6,
    "TD": 0,
    "LNG": 22,
    "BIG": 2,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 4,
    "PCT": "40.00%"
  },
  
    "Barner, Kenjon": {
    "GP": 13,
    "ATT": 16,
    "ATT/G": 1.2,
    "YDS": 14,
    "AVG": 3.6,
    "YDS/G": 4.4,
    "TD": 1,
    "LNG": 18,
    "BIG": 2,
    "100+": 0,
    "STUFF": 3,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "18.80%"
  },
  
    "Woodhead, Danny": {
    "GP": 8,
    "ATT": 14,
    "ATT/G": 1.8,
    "YDS": 0,
    "AVG": 4,
    "YDS/G": 7,
    "TD": 0,
    "LNG": 10,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "14.30%"
  },
  
    "Ellington, Andre": {
    "GP": 12,
    "ATT": 20,
    "ATT/G": 1.7,
    "YDS": 11,
    "AVG": 2.8,
    "YDS/G": 4.6,
    "TD": 1,
    "LNG": 14,
    "BIG": 1,
    "100+": 0,
    "STUFF": 5,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "15.00%"
  },
  
    "Petty, Bryce": {
    "GP": 4,
    "ATT": 7,
    "ATT/G": 1.8,
    "YDS": 0,
    "AVG": 7.9,
    "YDS/G": 13.8,
    "TD": 0,
    "LNG": 24,
    "BIG": 2,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 4,
    "PCT": "57.10%"
  },
  
    "Jackson, Adoree'": {
    "GP": 16,
    "ATT": 5,
    "ATT/G": 0.3,
    "YDS": 3,
    "AVG": 11,
    "YDS/G": 3.4,
    "TD": 0,
    "LNG": 20,
    "BIG": 3,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "60.00%"
  },
  
    "Flacco, Joe": {
    "GP": 16,
    "ATT": 25,
    "ATT/G": 1.6,
    "YDS": 0,
    "AVG": 2.2,
    "YDS/G": 3.4,
    "TD": 1,
    "LNG": 25,
    "BIG": 2,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 3,
    "PCT": "12.00%"
  },
  
    "Webb, Joe": {
    "GP": 16,
    "ATT": 8,
    "ATT/G": 0.5,
    "YDS": 0,
    "AVG": 6.8,
    "YDS/G": 3.4,
    "TD": 0,
    "LNG": 22,
    "BIG": 2,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 4,
    "PCT": "50.00%"
  },
  
    "Turbin, Robert": {
    "GP": 6,
    "ATT": 23,
    "ATT/G": 3.8,
    "YDS": 9,
    "AVG": 2.3,
    "YDS/G": 8.8,
    "TD": 1,
    "LNG": 7,
    "BIG": 0,
    "100+": 0,
    "STUFF": 4,
    "FUM": 0,
    "FUML": 0,
    "1ST": 9,
    "PCT": "39.10%"
  },
  
    "Yates, T.J.": {
    "GP": 4,
    "ATT": 5,
    "ATT/G": 1.3,
    "YDS": 0,
    "AVG": 10.2,
    "YDS/G": 12.8,
    "TD": 0,
    "LNG": 15,
    "BIG": 3,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 4,
    "PCT": "80.00%"
  },
  
    "Dunbar, Lance": {
    "GP": 4,
    "ATT": 11,
    "ATT/G": 2.8,
    "YDS": 3,
    "AVG": 4.6,
    "YDS/G": 12.8,
    "TD": 1,
    "LNG": 12,
    "BIG": 2,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 4,
    "PCT": "36.40%"
  },
  
    "Goff, Jared": {
    "GP": 15,
    "ATT": 28,
    "ATT/G": 1.9,
    "YDS": 7,
    "AVG": 1.8,
    "YDS/G": 3.4,
    "TD": 1,
    "LNG": 22,
    "BIG": 1,
    "100+": 0,
    "STUFF": 1,
    "FUM": 1,
    "FUML": 1,
    "1ST": 3,
    "PCT": "10.70%"
  },
  
    "Gabriel, Taylor": {
    "GP": 16,
    "ATT": 8,
    "ATT/G": 0.5,
    "YDS": 5,
    "AVG": 6.1,
    "YDS/G": 3.1,
    "TD": 0,
    "LNG": 15,
    "BIG": 2,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "37.50%"
  },
  
    "Edmunds, Trey": {
    "GP": 16,
    "ATT": 9,
    "ATT/G": 0.6,
    "YDS": 5,
    "AVG": 5.3,
    "YDS/G": 3,
    "TD": 1,
    "LNG": 41,
    "BIG": 1,
    "100+": 0,
    "STUFF": 3,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "11.10%"
  },
  
    "Roethlisberger, Ben": {
    "GP": 15,
    "ATT": 28,
    "ATT/G": 1.9,
    "YDS": 0,
    "AVG": 1.7,
    "YDS/G": 3.1,
    "TD": 0,
    "LNG": 14,
    "BIG": 2,
    "100+": 0,
    "STUFF": 0,
    "FUM": 2,
    "FUML": 0,
    "1ST": 6,
    "PCT": "21.40%"
  },
  
    "Goodwin, Marquise": {
    "GP": 16,
    "ATT": 4,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 11,
    "YDS/G": 2.8,
    "TD": 0,
    "LNG": 18,
    "BIG": 3,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "75.00%"
  },
  
    "Washington, Dwayne": {
    "GP": 5,
    "ATT": 20,
    "ATT/G": 4,
    "YDS": 8,
    "AVG": 2.2,
    "YDS/G": 8.8,
    "TD": 0,
    "LNG": 6,
    "BIG": 0,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "5.00%"
  },
  
    "Olawale, Jamize": {
    "GP": 12,
    "ATT": 9,
    "ATT/G": 0.8,
    "YDS": 0,
    "AVG": 4.8,
    "YDS/G": 3.6,
    "TD": 1,
    "LNG": 11,
    "BIG": 2,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 5,
    "PCT": "55.60%"
  },
  
    "Taylor, Taywan": {
    "GP": 16,
    "ATT": 8,
    "ATT/G": 0.5,
    "YDS": 2,
    "AVG": 5.4,
    "YDS/G": 2.7,
    "TD": 0,
    "LNG": 17,
    "BIG": 1,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "12.50%"
  },
  
    "Campanaro, Michael": {
    "GP": 13,
    "ATT": 5,
    "ATT/G": 0.4,
    "YDS": 0,
    "AVG": 8.4,
    "YDS/G": 3.2,
    "TD": 0,
    "LNG": 19,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "40.00%"
  },
  
    "Murphy, Marcus": {
    "GP": 1,
    "ATT": 7,
    "ATT/G": 7,
    "YDS": 4,
    "AVG": 5.9,
    "YDS/G": 41,
    "TD": 0,
    "LNG": 25,
    "BIG": 1,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "28.60%"
  },
  
    "Sherman, Anthony": {
    "GP": 16,
    "ATT": 14,
    "ATT/G": 0.9,
    "YDS": 2,
    "AVG": 2.9,
    "YDS/G": 2.5,
    "TD": 1,
    "LNG": 9,
    "BIG": 0,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 5,
    "PCT": "35.70%"
  },
  
    "Cooks, Brandin": {
    "GP": 16,
    "ATT": 9,
    "ATT/G": 0.6,
    "YDS": 11,
    "AVG": 4.4,
    "YDS/G": 2.5,
    "TD": 0,
    "LNG": 13,
    "BIG": 3,
    "100+": 0,
    "STUFF": 3,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "22.20%"
  },
  
    "Ginn Jr., Ted": {
    "GP": 15,
    "ATT": 10,
    "ATT/G": 0.7,
    "YDS": 16,
    "AVG": 3.9,
    "YDS/G": 2.6,
    "TD": 0,
    "LNG": 15,
    "BIG": 2,
    "100+": 0,
    "STUFF": 3,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "20.00%"
  },
  
    "Jackson, DeSean": {
    "GP": 14,
    "ATT": 3,
    "ATT/G": 0.2,
    "YDS": 0,
    "AVG": 12.7,
    "YDS/G": 2.7,
    "TD": 0,
    "LNG": 23,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "33.30%"
  },
  
    "Nelson, J.J.": {
    "GP": 16,
    "ATT": 3,
    "ATT/G": 0.2,
    "YDS": 0,
    "AVG": 12.3,
    "YDS/G": 2.3,
    "TD": 0,
    "LNG": 16,
    "BIG": 2,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "66.70%"
  },
  
    "Hill, Brian": {
    "GP": 7,
    "ATT": 11,
    "ATT/G": 1.6,
    "YDS": 2,
    "AVG": 3.4,
    "YDS/G": 5.3,
    "TD": 0,
    "LNG": 11,
    "BIG": 1,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "18.20%"
  },
  
    "Crowder, Jamison": {
    "GP": 15,
    "ATT": 7,
    "ATT/G": 0.5,
    "YDS": 1,
    "AVG": 4.9,
    "YDS/G": 2.3,
    "TD": 0,
    "LNG": 11,
    "BIG": 1,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "14.30%"
  },
  
    "Williams, Chad": {
    "GP": 6,
    "ATT": 2,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 16.5,
    "YDS/G": 5.5,
    "TD": 0,
    "LNG": 33,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "50.00%"
  },
  
    "Cutler, Jay": {
    "GP": 14,
    "ATT": 19,
    "ATT/G": 1.4,
    "YDS": 0,
    "AVG": 1.7,
    "YDS/G": 2.3,
    "TD": 0,
    "LNG": 9,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 2,
    "FUML": 0,
    "1ST": 3,
    "PCT": "15.80%"
  },
  
    "Heyward-Bey, Darrius": {
    "GP": 16,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 16,
    "YDS/G": 2,
    "TD": 1,
    "LNG": 29,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "50.00%"
  },
  
    "Marshall, Byron": {
    "GP": 4,
    "ATT": 9,
    "ATT/G": 2.3,
    "YDS": 3,
    "AVG": 3.6,
    "YDS/G": 8,
    "TD": 0,
    "LNG": 11,
    "BIG": 1,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "11.10%"
  },
  
    "Juszczyk, Kyle": {
    "GP": 14,
    "ATT": 7,
    "ATT/G": 0.5,
    "YDS": 0,
    "AVG": 4.4,
    "YDS/G": 2.2,
    "TD": 0,
    "LNG": 12,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 4,
    "PCT": "57.10%"
  },
  
    "Perry, Senorise": {
    "GP": 16,
    "ATT": 8,
    "ATT/G": 0.5,
    "YDS": 3,
    "AVG": 3.8,
    "YDS/G": 1.9,
    "TD": 0,
    "LNG": 12,
    "BIG": 1,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "25.00%"
  },
  
    "Mostert, Raheem": {
    "GP": 11,
    "ATT": 6,
    "ATT/G": 0.5,
    "YDS": 0,
    "AVG": 5,
    "YDS/G": 2.7,
    "TD": 0,
    "LNG": 16,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 1,
    "1ST": 1,
    "PCT": "16.70%"
  },
  
    "Lynch, Paxton": {
    "GP": 2,
    "ATT": 5,
    "ATT/G": 2.5,
    "YDS": 0,
    "AVG": 6,
    "YDS/G": 15,
    "TD": 0,
    "LNG": 11,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "40.00%"
  },
  
    "Cunningham, Benny": {
    "GP": 14,
    "ATT": 9,
    "ATT/G": 0.6,
    "YDS": 1,
    "AVG": 3.2,
    "YDS/G": 2.1,
    "TD": 0,
    "LNG": 12,
    "BIG": 1,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "11.10%"
  },
  
    "Brown, Mack": {
    "GP": 4,
    "ATT": 8,
    "ATT/G": 2,
    "YDS": 2,
    "AVG": 3.6,
    "YDS/G": 7.3,
    "TD": 0,
    "LNG": 11,
    "BIG": 1,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "12.50%"
  },
  
    "Brady, Tom": {
    "GP": 16,
    "ATT": 25,
    "ATT/G": 1.6,
    "YDS": 0,
    "AVG": 1.1,
    "YDS/G": 1.8,
    "TD": 0,
    "LNG": 7,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 1,
    "1ST": 7,
    "PCT": "28.00%"
  },
  
    "Line, Zach": {
    "GP": 12,
    "ATT": 7,
    "ATT/G": 0.6,
    "YDS": 0,
    "AVG": 4,
    "YDS/G": 2.3,
    "TD": 0,
    "LNG": 9,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 5,
    "PCT": "71.40%"
  },
  
    "Clay, Kaelin": {
    "GP": 13,
    "ATT": 3,
    "ATT/G": 0.2,
    "YDS": 2,
    "AVG": 9,
    "YDS/G": 2.1,
    "TD": 0,
    "LNG": 29,
    "BIG": 1,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "33.30%"
  },
  
    "Stewart, ArDarius": {
    "GP": 15,
    "ATT": 7,
    "ATT/G": 0.5,
    "YDS": 1,
    "AVG": 3.9,
    "YDS/G": 1.8,
    "TD": 0,
    "LNG": 11,
    "BIG": 1,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "28.60%"
  },
  
    "Manning, Eli": {
    "GP": 15,
    "ATT": 12,
    "ATT/G": 0.8,
    "YDS": 0,
    "AVG": 2.2,
    "YDS/G": 1.7,
    "TD": 1,
    "LNG": 14,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 2,
    "PCT": "16.70%"
  },
  
    "Zenner, Zach": {
    "GP": 8,
    "ATT": 14,
    "ATT/G": 1.8,
    "YDS": 8,
    "AVG": 1.9,
    "YDS/G": 3.3,
    "TD": 1,
    "LNG": 14,
    "BIG": 1,
    "100+": 0,
    "STUFF": 3,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "14.30%"
  },
  
    "Williams, Andre": {
    "GP": 8,
    "ATT": 9,
    "ATT/G": 1.1,
    "YDS": 2,
    "AVG": 2.8,
    "YDS/G": 3.1,
    "TD": 0,
    "LNG": 7,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Toussaint, Fitzgerald": {
    "GP": 6,
    "ATT": 6,
    "ATT/G": 1,
    "YDS": 0,
    "AVG": 4.2,
    "YDS/G": 4.2,
    "TD": 0,
    "LNG": 7,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "16.70%"
  },
  
    "Jones, Chris": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 24,
    "YDS/G": 1.5,
    "TD": 0,
    "LNG": 24,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Watt, Derek": {
    "GP": 16,
    "ATT": 6,
    "ATT/G": 0.4,
    "YDS": 0,
    "AVG": 4,
    "YDS/G": 1.5,
    "TD": 0,
    "LNG": 17,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "33.30%"
  },
  
    "Johnson, David": {
    "GP": 1,
    "ATT": 11,
    "ATT/G": 11,
    "YDS": 2,
    "AVG": 2.1,
    "YDS/G": 23,
    "TD": 0,
    "LNG": 6,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 1,
    "FUML": 1,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Hunt, Akeem": {
    "GP": 15,
    "ATT": 8,
    "ATT/G": 0.5,
    "YDS": 10,
    "AVG": 2.9,
    "YDS/G": 1.5,
    "TD": 0,
    "LNG": 11,
    "BIG": 1,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "12.50%"
  },
  
    "Prosise, C.J.": {
    "GP": 5,
    "ATT": 11,
    "ATT/G": 2.2,
    "YDS": 2,
    "AVG": 2.1,
    "YDS/G": 4.6,
    "TD": 0,
    "LNG": 8,
    "BIG": 0,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "9.10%"
  },
  
    "Peterman, Nathan": {
    "GP": 4,
    "ATT": 7,
    "ATT/G": 1.8,
    "YDS": 0,
    "AVG": 3.3,
    "YDS/G": 5.8,
    "TD": 0,
    "LNG": 9,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 2,
    "FUML": 0,
    "1ST": 1,
    "PCT": "14.30%"
  },
  
    "Tate, Golden": {
    "GP": 16,
    "ATT": 5,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 4.4,
    "YDS/G": 1.4,
    "TD": 0,
    "LNG": 10,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "20.00%"
  },
  
    "Bryant, Martavis": {
    "GP": 15,
    "ATT": 6,
    "ATT/G": 0.4,
    "YDS": 9,
    "AVG": 3.7,
    "YDS/G": 1.5,
    "TD": 0,
    "LNG": 13,
    "BIG": 1,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Sudfeld, Nate": {
    "GP": 1,
    "ATT": 1,
    "ATT/G": 1,
    "YDS": 0,
    "AVG": 22,
    "YDS/G": 22,
    "TD": 0,
    "LNG": 22,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Fluellen, David": {
    "GP": 16,
    "ATT": 4,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 5.3,
    "YDS/G": 1.3,
    "TD": 0,
    "LNG": 10,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "25.00%"
  },
  
    "Shepard, Russell": {
    "GP": 15,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 9.5,
    "YDS/G": 1.3,
    "TD": 0,
    "LNG": 11,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "50.00%"
  },
  
    "Foster, D.J.": {
    "GP": 7,
    "ATT": 6,
    "ATT/G": 0.9,
    "YDS": 0,
    "AVG": 3.2,
    "YDS/G": 2.7,
    "TD": 0,
    "LNG": 5,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Whittaker, Fozzy": {
    "GP": 12,
    "ATT": 7,
    "ATT/G": 0.6,
    "YDS": 3,
    "AVG": 2.6,
    "YDS/G": 1.5,
    "TD": 0,
    "LNG": 8,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "28.60%"
  },
  
    "Cobb, Randall": {
    "GP": 15,
    "ATT": 9,
    "ATT/G": 0.6,
    "YDS": 7,
    "AVG": 1.9,
    "YDS/G": 1.1,
    "TD": 0,
    "LNG": 10,
    "BIG": 1,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "11.10%"
  },
  
    "Hogan, Chris": {
    "GP": 9,
    "ATT": 3,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 5.7,
    "YDS/G": 1.9,
    "TD": 0,
    "LNG": 13,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "33.30%"
  },
  
    "Lee, Marqise": {
    "GP": 14,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 17,
    "YDS/G": 1.2,
    "TD": 0,
    "LNG": 17,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Ellington, Bruce": {
    "GP": 11,
    "ATT": 3,
    "ATT/G": 0.3,
    "YDS": 1,
    "AVG": 5.7,
    "YDS/G": 1.5,
    "TD": 0,
    "LNG": 13,
    "BIG": 1,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "33.30%"
  },
  
    "Reedy, Bernard": {
    "GP": 11,
    "ATT": 3,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 5.7,
    "YDS/G": 1.5,
    "TD": 0,
    "LNG": 10,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "33.30%"
  },
  
    "Erickson, Alex": {
    "GP": 16,
    "ATT": 5,
    "ATT/G": 0.3,
    "YDS": 7,
    "AVG": 3.2,
    "YDS/G": 1,
    "TD": 0,
    "LNG": 14,
    "BIG": 1,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "20.00%"
  },
  
    "Jones, Julio": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 15,
    "YDS/G": 0.9,
    "TD": 0,
    "LNG": 15,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Manuel, EJ": {
    "GP": 2,
    "ATT": 2,
    "ATT/G": 1,
    "YDS": 0,
    "AVG": 7.5,
    "YDS/G": 7.5,
    "TD": 0,
    "LNG": 10,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "50.00%"
  },
  
    "Williams, Terrance": {
    "GP": 16,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 7.5,
    "YDS/G": 0.9,
    "TD": 0,
    "LNG": 9,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "50.00%"
  },
  
    "Natson Jr., JoJo": {
    "GP": 7,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 15,
    "YDS/G": 2.1,
    "TD": 0,
    "LNG": 15,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Ebner, Nate": {
    "GP": 9,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 14,
    "YDS/G": 1.6,
    "TD": 0,
    "LNG": 14,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Gray, MarQueis": {
    "GP": 16,
    "ATT": 5,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 2.8,
    "YDS/G": 0.9,
    "TD": 0,
    "LNG": 5,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "60.00%"
  },
  
    "Jones, Matt": {
    "GP": 5,
    "ATT": 5,
    "ATT/G": 1,
    "YDS": 0,
    "AVG": 2.8,
    "YDS/G": 2.8,
    "TD": 0,
    "LNG": 5,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "20.00%"
  },
  
    "Lewis, Tommylee": {
    "GP": 15,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 7,
    "YDS/G": 0.9,
    "TD": 0,
    "LNG": 8,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Engram, Evan": {
    "GP": 15,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 14,
    "YDS/G": 0.9,
    "TD": 0,
    "LNG": 14,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Daniels Jr., LeShun": {
    "GP": 4,
    "ATT": 3,
    "ATT/G": 0.8,
    "YDS": 0,
    "AVG": 4.7,
    "YDS/G": 3.5,
    "TD": 0,
    "LNG": 8,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Diggs, Stefon": {
    "GP": 14,
    "ATT": 8,
    "ATT/G": 0.6,
    "YDS": 15,
    "AVG": 1.6,
    "YDS/G": 0.9,
    "TD": 0,
    "LNG": 9,
    "BIG": 0,
    "100+": 0,
    "STUFF": 3,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "12.50%"
  },
  
    "Ripkowski, Aaron": {
    "GP": 16,
    "ATT": 5,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 2.6,
    "YDS/G": 0.8,
    "TD": 0,
    "LNG": 4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Davis, Trevor": {
    "GP": 16,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 6.5,
    "YDS/G": 0.8,
    "TD": 0,
    "LNG": 9,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Ham, C.J.": {
    "GP": 16,
    "ATT": 7,
    "ATT/G": 0.4,
    "YDS": 0,
    "AVG": 1.9,
    "YDS/G": 0.8,
    "TD": 1,
    "LNG": 3,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 5,
    "PCT": "71.40%"
  },
  
    "Everett, Gerald": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 13,
    "YDS/G": 0.8,
    "TD": 0,
    "LNG": 13,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Henderson, De'Angelo": {
    "GP": 5,
    "ATT": 7,
    "ATT/G": 1.4,
    "YDS": 3,
    "AVG": 1.9,
    "YDS/G": 2.6,
    "TD": 0,
    "LNG": 5,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "28.60%"
  },
  
    "Dayes, Matthew": {
    "GP": 16,
    "ATT": 5,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 2.6,
    "YDS/G": 0.8,
    "TD": 0,
    "LNG": 4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "20.00%"
  },
  
    "Rush, Cooper": {
    "GP": 2,
    "ATT": 2,
    "ATT/G": 1,
    "YDS": 0,
    "AVG": 6.5,
    "YDS/G": 6.5,
    "TD": 0,
    "LNG": 15,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "50.00%"
  },
  
    "Brees, Drew": {
    "GP": 16,
    "ATT": 33,
    "ATT/G": 2.1,
    "YDS": 0,
    "AVG": 0.4,
    "YDS/G": 0.8,
    "TD": 2,
    "LNG": 7,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 2,
    "FUML": 0,
    "1ST": 7,
    "PCT": "21.20%"
  },
  
    "Palmer, Carson": {
    "GP": 7,
    "ATT": 14,
    "ATT/G": 2,
    "YDS": 0,
    "AVG": 0.9,
    "YDS/G": 1.7,
    "TD": 0,
    "LNG": 4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 2,
    "FUML": 0,
    "1ST": 5,
    "PCT": "35.70%"
  },
  
    "Woods, Robert": {
    "GP": 12,
    "ATT": 2,
    "ATT/G": 0.2,
    "YDS": 0,
    "AVG": 6,
    "YDS/G": 1,
    "TD": 0,
    "LNG": 8,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Smith, Geno": {
    "GP": 2,
    "ATT": 4,
    "ATT/G": 2,
    "YDS": 0,
    "AVG": 3,
    "YDS/G": 6,
    "TD": 0,
    "LNG": 10,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "50.00%"
  },
  
    "Byrd, Damiere": {
    "GP": 8,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 12,
    "YDS/G": 1.5,
    "TD": 0,
    "LNG": 12,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Ervin, Tyler": {
    "GP": 4,
    "ATT": 4,
    "ATT/G": 1,
    "YDS": 2,
    "AVG": 3,
    "YDS/G": 3,
    "TD": 0,
    "LNG": 6,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "25.00%"
  },
  
    "Janovich, Andy": {
    "GP": 16,
    "ATT": 6,
    "ATT/G": 0.4,
    "YDS": 1,
    "AVG": 2,
    "YDS/G": 0.8,
    "TD": 1,
    "LNG": 4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "50.00%"
  },
  
    "Grant, Jakeem": {
    "GP": 16,
    "ATT": 3,
    "ATT/G": 0.2,
    "YDS": 0,
    "AVG": 4,
    "YDS/G": 0.8,
    "TD": 0,
    "LNG": 7,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Ross, John": {
    "GP": 3,
    "ATT": 1,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 12,
    "YDS/G": 4,
    "TD": 0,
    "LNG": 12,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 1,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Thielen, Adam": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 11,
    "YDS/G": 0.7,
    "TD": 0,
    "LNG": 11,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Garoppolo, Jimmy": {
    "GP": 6,
    "ATT": 15,
    "ATT/G": 2.5,
    "YDS": 3,
    "AVG": 0.7,
    "YDS/G": 1.8,
    "TD": 1,
    "LNG": 8,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 1,
    "FUML": 0,
    "1ST": 3,
    "PCT": "20.00%"
  },
  
    "Sanu, Mohamed": {
    "GP": 15,
    "ATT": 4,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 2.5,
    "YDS/G": 0.7,
    "TD": 0,
    "LNG": 4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "75.00%"
  },
  
    "Brown, John": {
    "GP": 10,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 10,
    "YDS/G": 1,
    "TD": 0,
    "LNG": 10,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Redfern, Kasey": {
    "GP": 1,
    "ATT": 1,
    "ATT/G": 1,
    "YDS": 0,
    "AVG": 10,
    "YDS/G": 10,
    "TD": 0,
    "LNG": 10,
    "BIG": 1,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Mahomes II, Patrick": {
    "GP": 1,
    "ATT": 7,
    "ATT/G": 7,
    "YDS": 0,
    "AVG": 1.4,
    "YDS/G": 10,
    "TD": 0,
    "LNG": 5,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Moore, Matt": {
    "GP": 4,
    "ATT": 3,
    "ATT/G": 0.8,
    "YDS": 0,
    "AVG": 3,
    "YDS/G": 2.3,
    "TD": 0,
    "LNG": 7,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "33.30%"
  },
  
    "Allen, Keenan": {
    "GP": 16,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 4.5,
    "YDS/G": 0.6,
    "TD": 0,
    "LNG": 6,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Burton, Michael": {
    "GP": 16,
    "ATT": 4,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 2.3,
    "YDS/G": 0.6,
    "TD": 0,
    "LNG": 7,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "50.00%"
  },
  
    "Fuller V, Will": {
    "GP": 10,
    "ATT": 2,
    "ATT/G": 0.2,
    "YDS": 0,
    "AVG": 4.5,
    "YDS/G": 0.9,
    "TD": 0,
    "LNG": 5,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Anderson, Robby": {
    "GP": 16,
    "ATT": 3,
    "ATT/G": 0.2,
    "YDS": 0,
    "AVG": 3,
    "YDS/G": 0.6,
    "TD": 0,
    "LNG": 7,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Golladay, Kenny": {
    "GP": 11,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 9,
    "YDS/G": 0.8,
    "TD": 0,
    "LNG": 9,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Agnew, Jamal": {
    "GP": 13,
    "ATT": 2,
    "ATT/G": 0.2,
    "YDS": 0,
    "AVG": 4.5,
    "YDS/G": 0.7,
    "TD": 0,
    "LNG": 5,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "50.00%"
  },
  
    "Coleman, Derrick": {
    "GP": 16,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 4,
    "YDS/G": 0.5,
    "TD": 0,
    "LNG": 5,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Beckham Jr., Odell": {
    "GP": 4,
    "ATT": 1,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 8,
    "YDS/G": 2,
    "TD": 0,
    "LNG": 8,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Fales, David": {
    "GP": 2,
    "ATT": 4,
    "ATT/G": 2,
    "YDS": 0,
    "AVG": 2,
    "YDS/G": 4,
    "TD": 1,
    "LNG": 3,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "25.00%"
  },
  
    "Watson, Terrell": {
    "GP": 10,
    "ATT": 5,
    "ATT/G": 0.5,
    "YDS": 0,
    "AVG": 1.6,
    "YDS/G": 0.8,
    "TD": 0,
    "LNG": 3,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 3,
    "PCT": "60.00%"
  },
  
    "Rogers, Chester": {
    "GP": 11,
    "ATT": 3,
    "ATT/G": 0.3,
    "YDS": 2,
    "AVG": 2.7,
    "YDS/G": 0.7,
    "TD": 0,
    "LNG": 7,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Wilson, Bobo": {
    "GP": 3,
    "ATT": 3,
    "ATT/G": 1,
    "YDS": 4,
    "AVG": 2.7,
    "YDS/G": 2.7,
    "TD": 0,
    "LNG": 8,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Stanton, Drew": {
    "GP": 5,
    "ATT": 9,
    "ATT/G": 1.8,
    "YDS": 0,
    "AVG": 0.8,
    "YDS/G": 1.4,
    "TD": 0,
    "LNG": 5,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "22.20%"
  },
  
    "Kelce, Travis": {
    "GP": 15,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 3.5,
    "YDS/G": 0.5,
    "TD": 0,
    "LNG": 4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "100.00%"
  },
  
    "Agholor, Nelson": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 7,
    "YDS/G": 0.4,
    "TD": 0,
    "LNG": 7,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Dorsett, Phillip": {
    "GP": 15,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 7,
    "YDS/G": 0.5,
    "TD": 0,
    "LNG": 7,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Whitehead, Jermaine": {
    "GP": 10,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 7,
    "YDS/G": 0.7,
    "TD": 0,
    "LNG": 7,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Bellamy, Josh": {
    "GP": 15,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 6,
    "YDS/G": 0.4,
    "TD": 0,
    "LNG": 6,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Wilson, Albert": {
    "GP": 13,
    "ATT": 3,
    "ATT/G": 0.2,
    "YDS": 4,
    "AVG": 2,
    "YDS/G": 0.5,
    "TD": 0,
    "LNG": 6,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "33.30%"
  },
  
    "Williams, Maxx": {
    "GP": 11,
    "ATT": 2,
    "ATT/G": 0.2,
    "YDS": 0,
    "AVG": 3,
    "YDS/G": 0.5,
    "TD": 0,
    "LNG": 4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "100.00%"
  },
  
    "Humphries, Adam": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 6,
    "YDS/G": 0.4,
    "TD": 0,
    "LNG": 6,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Cooper, Pharoh": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 6,
    "YDS/G": 0.4,
    "TD": 0,
    "LNG": 6,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Treggs, Bryce": {
    "GP": 6,
    "ATT": 1,
    "ATT/G": 0.2,
    "YDS": 0,
    "AVG": 6,
    "YDS/G": 1,
    "TD": 0,
    "LNG": 6,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Bohanon, Tommy": {
    "GP": 16,
    "ATT": 5,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 1,
    "YDS/G": 0.3,
    "TD": 2,
    "LNG": 3,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 2,
    "PCT": "40.00%"
  },
  
    "Ferguson, Josh": {
    "GP": 10,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 5,
    "YDS/G": 0.5,
    "TD": 0,
    "LNG": 5,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Switzer, Ryan": {
    "GP": 16,
    "ATT": 4,
    "ATT/G": 0.3,
    "YDS": 4,
    "AVG": 1.3,
    "YDS/G": 0.3,
    "TD": 0,
    "LNG": 3,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Hollister, Jacob": {
    "GP": 15,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 5,
    "YDS/G": 0.3,
    "TD": 0,
    "LNG": 5,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Hoyer, Brian": {
    "GP": 11,
    "ATT": 9,
    "ATT/G": 0.8,
    "YDS": 5,
    "AVG": 0.4,
    "YDS/G": 0.4,
    "TD": 1,
    "LNG": 9,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 2,
    "FUML": 0,
    "1ST": 2,
    "PCT": "22.20%"
  },
  
    "Wallace, Mike": {
    "GP": 15,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 4,
    "YDS/G": 0.3,
    "TD": 0,
    "LNG": 4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Paul, Niles": {
    "GP": 14,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 1,
    "AVG": 2,
    "YDS/G": 0.3,
    "TD": 0,
    "LNG": 5,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "50.00%"
  },
  
    "Glennon, Mike": {
    "GP": 4,
    "ATT": 4,
    "ATT/G": 1,
    "YDS": 0,
    "AVG": 1,
    "YDS/G": 1,
    "TD": 0,
    "LNG": 2,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 2,
    "FUML": 1,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Thomas, De'Anthony": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 4,
    "YDS/G": 0.3,
    "TD": 0,
    "LNG": 4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Cooper, Amari": {
    "GP": 14,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 4,
    "YDS/G": 0.3,
    "TD": 0,
    "LNG": 4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Fowler, Jalston": {
    "GP": 10,
    "ATT": 2,
    "ATT/G": 0.2,
    "YDS": 0,
    "AVG": 2,
    "YDS/G": 0.4,
    "TD": 1,
    "LNG": 3,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "50.00%"
  },
  
    "Shepard, Sterling": {
    "GP": 11,
    "ATT": 4,
    "ATT/G": 0.4,
    "YDS": 14,
    "AVG": 1,
    "YDS/G": 0.4,
    "TD": 0,
    "LNG": 12,
    "BIG": 1,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "25.00%"
  },
  
    "Higgins, Rashard": {
    "GP": 15,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 4,
    "YDS/G": 0.3,
    "TD": 0,
    "LNG": 4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Lutz, Wil": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 4,
    "YDS/G": 0.3,
    "TD": 0,
    "LNG": 4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "McKenzie, Isaiah": {
    "GP": 11,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 4,
    "YDS/G": 0.4,
    "TD": 0,
    "LNG": 4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Foles, Nick": {
    "GP": 7,
    "ATT": 11,
    "ATT/G": 1.6,
    "YDS": 0,
    "AVG": 0.3,
    "YDS/G": 0.4,
    "TD": 0,
    "LNG": 9,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 3,
    "FUML": 1,
    "1ST": 1,
    "PCT": "9.10%"
  },
  
    "King, Tavarres": {
    "GP": 8,
    "ATT": 2,
    "ATT/G": 0.3,
    "YDS": 8,
    "AVG": 1.5,
    "YDS/G": 0.4,
    "TD": 0,
    "LNG": 11,
    "BIG": 1,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "50.00%"
  },
  
    "Kuhn, John": {
    "GP": 2,
    "ATT": 1,
    "ATT/G": 0.5,
    "YDS": 0,
    "AVG": 2,
    "YDS/G": 1,
    "TD": 0,
    "LNG": 2,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Tolzien, Scott": {
    "GP": 1,
    "ATT": 2,
    "ATT/G": 2,
    "YDS": 0,
    "AVG": 1,
    "YDS/G": 2,
    "TD": 0,
    "LNG": 3,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Rainey, Bobby": {
    "GP": 4,
    "ATT": 1,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 2,
    "YDS/G": 0.5,
    "TD": 0,
    "LNG": 2,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Savage, Tom": {
    "GP": 8,
    "ATT": 4,
    "ATT/G": 0.5,
    "YDS": 0,
    "AVG": 0.5,
    "YDS/G": 0.3,
    "TD": 0,
    "LNG": 3,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Berhe, Nat": {
    "GP": 15,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 2,
    "YDS/G": 0.1,
    "TD": 0,
    "LNG": 2,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Mayle, Vince": {
    "GP": 16,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 1,
    "YDS/G": 0.1,
    "TD": 1,
    "LNG": 2,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "50.00%"
  },
  
    "Heinicke, Taylor": {
    "GP": 1,
    "ATT": 1,
    "ATT/G": 1,
    "YDS": 0,
    "AVG": 2,
    "YDS/G": 2,
    "TD": 0,
    "LNG": 2,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Malone, Josh": {
    "GP": 11,
    "ATT": 2,
    "ATT/G": 0.2,
    "YDS": 2,
    "AVG": 1,
    "YDS/G": 0.2,
    "TD": 0,
    "LNG": 4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Williams, Kyle": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 1,
    "YDS/G": 0.1,
    "TD": 1,
    "LNG": 1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "100.00%"
  },
  
    "Miller, Braxton": {
    "GP": 11,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 1,
    "YDS/G": 0.1,
    "TD": 0,
    "LNG": 1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Thomas, Lawrence": {
    "GP": 14,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 0.5,
    "YDS/G": 0.1,
    "TD": 0,
    "LNG": 1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Njoku, David": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 1,
    "YDS/G": 0.1,
    "TD": 0,
    "LNG": 1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Mays, Devante": {
    "GP": 8,
    "ATT": 4,
    "ATT/G": 0.5,
    "YDS": 4,
    "AVG": 0.3,
    "YDS/G": 0.1,
    "TD": 0,
    "LNG": 2,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 2,
    "FUML": 1,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Davis, Justin": {
    "GP": 4,
    "ATT": 1,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": 1,
    "YDS/G": 0.3,
    "TD": 0,
    "LNG": 1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Weems, Eric": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 0,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Smith, Evan": {
    "GP": 15,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Unger, Max": {
    "GP": 16,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Spiller, C.J.": {
    "GP": 1,
    "ATT": 2,
    "ATT/G": 2,
    "YDS": 1,
    "AVG": 0,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Bosher, Matt": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 0,
    "AVG": 0,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Hudson, Rodney": {
    "GP": 16,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Pouncey, Mike": {
    "GP": 16,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Harris, Josh": {
    "GP": 16,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Kearse, Jermaine": {
    "GP": 16,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Tretter, JC": {
    "GP": 16,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Bray, Tyler": {
    "GP": 1,
    "ATT": 1,
    "ATT/G": 1,
    "YDS": 0,
    "AVG": 0,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 1,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Hubbard, Chris": {
    "GP": 16,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 2,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Devey, Jordan": {
    "GP": 9,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Jensen, Ryan": {
    "GP": 16,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Linsley, Corey": {
    "GP": 16,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Paradis, Matt": {
    "GP": 16,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Fulton, Zach": {
    "GP": 15,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 2,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Nix, Roosevelt": {
    "GP": 16,
    "ATT": 3,
    "ATT/G": 0.2,
    "YDS": 1,
    "AVG": 0,
    "YDS/G": 0,
    "TD": 1,
    "LNG": 1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "33.30%"
  },
  
    "Pulley, Spencer": {
    "GP": 16,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 2,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Bond, Deyshawn": {
    "GP": 4,
    "ATT": 0,
    "ATT/G": 0,
    "YDS": 0,
    "AVG": null,
    "YDS/G": 0,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 0,
    "PCT": null
  },
  
    "Davis, Austin": {
    "GP": 3,
    "ATT": 1,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": -1,
    "YDS/G": -0.3,
    "TD": 0,
    "LNG": -1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Kessler, Cody": {
    "GP": 3,
    "ATT": 1,
    "ATT/G": 0.3,
    "YDS": 0,
    "AVG": -1,
    "YDS/G": -0.3,
    "TD": 0,
    "LNG": -1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Raymond, Kalif": {
    "GP": 8,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 1,
    "AVG": -1,
    "YDS/G": -0.1,
    "TD": 0,
    "LNG": -1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Rivers, Philip": {
    "GP": 16,
    "ATT": 18,
    "ATT/G": 1.1,
    "YDS": 2,
    "AVG": -0.1,
    "YDS/G": -0.1,
    "TD": 0,
    "LNG": 8,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 3,
    "FUML": 0,
    "1ST": 1,
    "PCT": "5.60%"
  },
  
    "Anderson, Derek": {
    "GP": 3,
    "ATT": 2,
    "ATT/G": 0.7,
    "YDS": 0,
    "AVG": -1,
    "YDS/G": -0.7,
    "TD": 0,
    "LNG": -1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Walker, Delanie": {
    "GP": 16,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 3,
    "AVG": -1,
    "YDS/G": -0.1,
    "TD": 1,
    "LNG": 1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 1,
    "PCT": "50.00%"
  },
  
    "McFadden, Darren": {
    "GP": 1,
    "ATT": 1,
    "ATT/G": 1,
    "YDS": 2,
    "AVG": -2,
    "YDS/G": -2,
    "TD": 0,
    "LNG": -2,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Daniel, Chase": {
    "GP": 1,
    "ATT": 3,
    "ATT/G": 3,
    "YDS": 0,
    "AVG": -0.7,
    "YDS/G": -2,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "DiMarco, Patrick": {
    "GP": 16,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 2,
    "AVG": -1,
    "YDS/G": -0.1,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Mannion, Sean": {
    "GP": 5,
    "ATT": 9,
    "ATT/G": 1.8,
    "YDS": 0,
    "AVG": -0.2,
    "YDS/G": -0.4,
    "TD": 0,
    "LNG": 3,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 3,
    "PCT": "33.30%"
  },
  
    "Hill, Bronson": {
    "GP": 2,
    "ATT": 1,
    "ATT/G": 0.5,
    "YDS": 2,
    "AVG": -2,
    "YDS/G": -1,
    "TD": 0,
    "LNG": -2,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Bradford, Sam": {
    "GP": 2,
    "ATT": 2,
    "ATT/G": 1,
    "YDS": 0,
    "AVG": -1.5,
    "YDS/G": -1.5,
    "TD": 0,
    "LNG": -1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Smith, Torrey": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 3,
    "AVG": -3,
    "YDS/G": -0.2,
    "TD": 0,
    "LNG": -3,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Matthews, Rishard": {
    "GP": 14,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 3,
    "AVG": -3,
    "YDS/G": -0.2,
    "TD": 0,
    "LNG": -3,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Mallett, Ryan": {
    "GP": 2,
    "ATT": 4,
    "ATT/G": 2,
    "YDS": 0,
    "AVG": -0.8,
    "YDS/G": -1.5,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 1,
    "FUML": 0,
    "1ST": 1,
    "PCT": "25.00%"
  },
  
    "Bridgewater, Teddy": {
    "GP": 1,
    "ATT": 3,
    "ATT/G": 3,
    "YDS": 0,
    "AVG": -1,
    "YDS/G": -3,
    "TD": 0,
    "LNG": -1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Bryant, Dez": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 4,
    "AVG": -4,
    "YDS/G": -0.3,
    "TD": 0,
    "LNG": -4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Clemens, Kellen": {
    "GP": 8,
    "ATT": 5,
    "ATT/G": 0.6,
    "YDS": 0,
    "AVG": -1,
    "YDS/G": -0.6,
    "TD": 0,
    "LNG": -1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Henne, Chad": {
    "GP": 2,
    "ATT": 5,
    "ATT/G": 2.5,
    "YDS": 0,
    "AVG": -1,
    "YDS/G": -2.5,
    "TD": 0,
    "LNG": -1,
    "BIG": 0,
    "100+": 0,
    "STUFF": 0,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Thompson, Deonte": {
    "GP": 16,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 5,
    "AVG": -2.5,
    "YDS/G": -0.3,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Landry, Jarvis": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 7,
    "AVG": -7,
    "YDS/G": -0.4,
    "TD": 0,
    "LNG": -7,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Baldwin, Doug": {
    "GP": 16,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 8,
    "AVG": -4,
    "YDS/G": -0.5,
    "TD": 0,
    "LNG": -3,
    "BIG": 0,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Hill, Josh": {
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 8,
    "AVG": -8,
    "YDS/G": -0.5,
    "TD": 0,
    "LNG": -8,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Moore, Chris": {
    "GP": 13,
    "ATT": 2,
    "ATT/G": 0.2,
    "YDS": 9,
    "AVG": -4.5,
    "YDS/G": -0.7,
    "TD": 0,
    "LNG": -4,
    "BIG": 0,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Jones, Landry": {
    "GP": 3,
    "ATT": 8,
    "ATT/G": 2.7,
    "YDS": 6,
    "AVG": -1.3,
    "YDS/G": -3.3,
    "TD": 0,
    "LNG": 0,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "King, Marquette": {
    "GP": 16,
    "ATT": 2,
    "ATT/G": 0.1,
    "YDS": 14,
    "AVG": -7,
    "YDS/G": -0.9,
    "TD": 0,
    "LNG": -3,
    "BIG": 0,
    "100+": 0,
    "STUFF": 2,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  },
  
    "Doctson, Josh":{
    "GP": 16,
    "ATT": 1,
    "ATT/G": 0.1,
    "YDS": 14,
    "AVG": -14,
    "YDS/G": -0.9,
    "TD": 0,
    "LNG": -14,
    "BIG": 0,
    "100+": 0,
    "STUFF": 1,
    "FUM": 0,
    "FUML": 0,
    "1ST": 0,
    "PCT": "0.00%"
  }
}